name: clm_trujillo_app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.2
  flutter_native_splash: 2.2.19
  flutter_svg: 2.0.5
  boxicons: 2.1.3
  url_launcher: 6.0.20
  share_plus: 6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0

flutter_native_splash:
  color: "#121212"
  image: assets/logo/clm-darklogo.png

  android_12:
    icon_background_color: "#121212"
    image: assets/logo/clm-darklogo.png

  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/icons/
    - assets/icons/app_icons/
    - assets/icons/main_icons/
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/images/welcome_images/
    - assets/images/home_images/
    - assets/images/service_times_images/
    - assets/images/invitation_images/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/dm_sans/DMSans-Regular.ttf
        - asset: assets/fonts/dm_sans/DMSans-Medium.ttf
        - asset: assets/fonts/dm_sans/DMSans-Bold.ttf

    - family: AlexBrush
      fonts:
        - asset: assets/fonts/alex_brush/AlexBrush-Regular.ttf
